export const REGISTER_ERR = "REGISTER_ERR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const SUCCESS_MESSAGE_CLEAR = "SUCCESS_MESSAGE_CLEAR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";